version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/vanilla-template/{{ cookiecutter.repo_name }}"
    schedule:
      interval: "monthly"
