name: Update precommit

on: [workflow_dispatch]

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: update pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit autoupdate -c "vanilla-template/{{ cookiecutter.repo_name }}/.pre-commit-config.yaml"

      - name: create pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Auto-update pre-commit hooks"
