name: Update precommit
on: [workflow_dispatch]

jobs:
  autoUpdate:
    strategy:
      matrix:
        config-path:
          [
            "vanilla-template/{{ cookiecutter.repo_name }}/.pre-commit-config.yaml",
          ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: update pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit autoupdate -c "${{ matrix.config-path }}"

      - name: create pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update pre-commit hooks
          title: "New versions to pre-commit hooks"
          branch: pre-commit-autoupdates
          delete-branch: true
          reviewers: nybyhansen
          labels: dependencies
