name: Update pre-commit hooks
on:
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  updatePrecommit:
    strategy:
      matrix:
        config-path:
          [
            "vanilla-template/{{ cookiecutter.repo_name }}/.pre-commit-config.yaml",
            ".pre-commit-config.yaml",
          ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - id: name
        run: |
          if [ "${{ matrix.config-path }}" == ".pre-commit-config.yaml" ]
          then
            NAME="outer-project"
          else
            NAME="template"
          fi
          echo "branch-suffix=$NAME" >> "$GITHUB_OUTPUT"

      - name: update pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit autoupdate -c "${{ matrix.config-path }}"

      - name: create pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update pre-commit hooks
          title: "Updates to pre-commit hooks | ${{ steps.name.outputs.branch-suffix }}"
          body: |
            Version updates to one or more pre-commit hooks.

            This PR is auto-generated.
          branch: pre-commit-autoupdates-${{ steps.name.outputs.branch-suffix }}
          delete-branch: true
          comitter: nybyhansen
          reviewers: nybyhansen
          labels: dependencies
